# 服务相关配置
server:
  port: 80

# dubbo服务配置信息
spring:
  dubbo:
    application:
      name: web-controller-consumer
    registry:
      address: zookeeper://192.168.137.2:2181
    scan: org.ys.soft.web.service
    monitor:
      protocol: registry